### ISSUE TITLE
Fingerprint dialog

### ISSUE THREAD

**Issue by frankyxcs** [jsoriase/EasyFingerprint#1]
Hi !

this is a very good work from you !!! I have tested it out and the only problem is if i delete my fingerprint and start the app again a dialog will be shown up with "fingerprint aborted". Normally there shouldn´t be a window if the fingerprint is deleted. 

maybe you can fix this ?

**Comment by jsoriase** [comment]
Seems that this is happening when you access the fingerprint settings, you don't even need to delete the fingerprint. I'll look into it.

Thanks!

**Comment by frankyxcs** [comment]
Hi 
i will try a fix now i will change in EasyFingerprint.java
 if (fingerManager.isHardwareDetected()) {
to 

 if (fingerManager.isHardwareDetected() fingerManager.hasEnrolledFingerprints()) {

maybe this could be the fix

**Comment by jsoriase** [comment]
You're right, I wasn't taking into account if the user had enrolled fingerprints!!

The issue is that android cancels the autentication when you access the fingerprint settings menu, sending an error with id 5 (FingerprintDialogActivity - onAuthenticationError()).

This was not doing anything but showing an error in the dialog. I'm going to modify it so the dialog is closed when this error appears.

Regards and thanks for your help!
